import { type ReactNode } from 'react';
import { Inter } from "next/font/google";
import { TrpcProvider } from '@/components/TrpcProvider';
import { AuthProvider } from '@/components/AuthProvider';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Trello on Rails",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TrpcProvider>
          <AuthProvider>
            {children}
          </AuthProvider>
        </TrpcProvider>
      </body>
    </html>
  );
}