import { type PropsWithChildren } from 'react';
import { Inter } from "next/font/google";
import { TrpcProvider } from '@/components/TrpcProvider';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Trello on Rails",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <TrpcProvider>
        <body className={inter.className}>{children}</body>
      </TrpcProvider>
    </html>
  );
}